apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    run: influxdb
spec:
  ports:
  - port: 8086
    protocol: TCP
    name: http
  selector:
    app: influxdb-app
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
data:
  INFLUXDB_DB: aW5mbHV4ZGI=
  INFLUXDB_USER: c3Nlbw==
  INFLUXDB_PASSWORD: aW5mbHV4ZGJwYXNzd29yZA==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      restartPolicy: Always
      volumes:
      - name: influxdb-persistent-volume
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      containers:
      - name: influxdb
        image: sseo_influxdb:1.0
        imagePullPolicy: Never
        env:
        - name: INFLUXDB_DB
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_DB
        - name: INFLUXDB_USER
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_USER
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_PASSWORD
        volumeMounts:
        - name: influxdb-persistent-volume
          mountPath: /var/lib/influxdb
