apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    run: influxdb
spec:
  type: LoadBalancer
  ports:
  - port: 8086
    protocol: TCP
    name: http
  selector:
    app: influxdb-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb-app
    spec:
      restartPolicys: always
      volumes:
      - name: influxdb-persistent-volume
        presistentVolumeClaim:
          claimName: influxdb-pv-claim
      containers:
      - name: influxdb
        image: sseo_influxdb:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-persistent-volume
          mountPath: /var/lib/influxdb
