apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    run: mysql
spec:
  ports:
    - port: 3306
      protocol: TCP
      name: http
  selector:
    app: mysql-app
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  PMA_USER: c3Nlbw==
  PMA_PASSWORD: cGFzc3dvcmQ=
  WP_USER: d29yZHByZXNz
  WP_PASSWORD: c3Ryb25ncGFzc3dvcmQ=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      restartPolicy: Always
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: sseo_mysql:1.0
        imagePullPolicy: Never
        env:
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: PMA_USER
        - name: PMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: PMA_PASSWORD
        - name: WP_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: WP_USER
        - name: WP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: WP_PASSWORD
        volumeMounts:
        - name: mysql-persistent-volume
          mountPath: /var/lib/mysql
