apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    run: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: mysql
    tier: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: c3VwZXItc2VjcmV0LXBhc3N3b3jk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: backend
#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
#      restartPolicy: Always
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      - name: mysql
        image: sseo_mysql:1.0
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD
#        - name: MYSQL_USER
#          value: sseo
#        - name: MYSQL_PASSWORD
#          value: test
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-volume
          mountPath: /var/lib/mysql
