apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP 
      name: https
    - port: 30020
      protocol: TCP
      name: ssh
  selector:
    app: nginx-app
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssh-user
type: Opaque
data:
  SSH_USER: c3Nlbw==
  SSH_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      volumes:
      - name: nginx-secrets
        secret:
          secretName: nginx-secrets
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: sseo_nginx:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 30020
        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: nginx-ssh-user
              key: SSH_USER
        - name: SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nginx-ssh-user
              key: SSH_PASSWORD
        volumeMounts:
        - name: nginx-secrets
          mountPath: /etc/ssl
        - name: nginx-config
          mountPath: /etc/nginx
