apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    run: wordpress
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    protocol: TCP
    name: http
  selector:
    app: wordpress-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      volumes:
      - name: wordpress-persistent-volume
        persistentVolumeClaim:
          claimName: wp-pv-claim
      containers:
      - name: wordpress
        image: sseo_wordpress:1.0
        imagePullPolicy: Never
        env:
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: WP_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: WP_PASSWORD
        volumeMounts:
        - name: wordpress-persistent-volume
          mountPath: /wordpress
