apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  labels:
    run: telegraf
spec:
  selector:
    app: telegraf-app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-app
  template:
    metadata:
      labels:
        app: telegraf-app
    spec:
      serviceAccountName: service-access
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
      containers:
      - name: telegraf
        image: sseo_telegraf:1.0
        imagePullPolicy: Never
        env:
        - name: INFLUXDB_DB
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_DB
        - name: INFLUXDB_USER
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_USER
        - name: INFLUXDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: influxdb-secrets
              key: INFLUXDB_PASSWORD
        volumeMounts:
          - name: telegraf-config
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
            readOnly: true
