apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  labels:
    run: telegraf
spec:
  type: LoadBalancer
  ports:
  - port: 4999
    protocol: TCP
    name: http
  selector:
    app: telegraf-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf-app
  template:
    metadata:
      labels:
        app: telegraf-app
    spec:
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: telegraf
        image: sseo_telegraf:1.0
        imagePullPolicy: Never
        env:
        - name: USER
          value: telegraf
        - name: INFLUX_URL
          value: "http://IP:8086"
        - name: INFLUX_SKIP_DATABASE_CREATION
          value: "false"
        - name: INFLUX_PASSWORD
          value: "services"
        ports:
        - containerPort: 4999
        volumeMounts:
        - name: docker-sock
          mountPath: "/var/run/docker.sock"
