apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    run: ftps
spec:
  ports:
    - port: 21
      protocol: TCP
      name: ftps
    - port: 20
      protocol: TCP
      name: ftps-data
    - port: 30021
      protocol: TCP
      name: ftps-psv1
    - port: 30022
      protocol: TCP
      name: ftps-psv2
    - port: 30023
      protocol: TCP
      name: ftps-psv3
    - port: 30024
      protocol: TCP
      name: ftps-psv4
    - port: 30025
      protocol: TCP
      name: ftps-psv5
  selector:
    app: ftps-app
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: ftps-user
type: Opaque
data:
  FTPS_USER: c3Nlbw==
  FTPS_PASSWORD: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps-app
spec:
  selector:
    matchLabels:
      app: ftps-app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      serviceAccount: service-access
      volumes:
      - name: ftps-secrets
        secret:
          secretName: ftps-secrets
      containers:
      - image: sseo_ftps:1.0
        imagePullPolicy: Never
        name: ftps
        env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftps-user
              key: FTPS_USER
        - name: FTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ftps-user
              key: FTPS_PASSWORD
        volumeMounts:
        - name: ftps-secrets
          mountPath: /etc/ssl/private
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-viewer
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-viewer
subjects:
- kind: ServiceAccount
  name: service-access
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-access
  labels:
    app: service-access-app
